name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install JPPM
      run: wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.4.1/jppm-setup-0.4.1.sh | sudo bash
    - name: Build
      run: jppm build
